# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoolTunes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoolTunes
  pod 'SDWebImage', '~> 5.9'

  target 'CoolTunesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
